language: node_js
node_js:
- 8.11.1
env:
- NODE_ENV=test
services:
- postgresql
before_script:
- psql -c 'create database blog;' -U postgres
- "./node_modules/.bin/sequelize db:migrate"
deploy:
  provider: heroku
  api_key:
    secure: Yq7XiBsK06VW6kz7JOL5efP+aCnpXKX18lgr+iWDUAde+O8m2rCIaMCQd1CNa/Ec8jB72WE3T8hbV6QododrvHp5uQC/O2KMA/Hpqts5XvxbKE5sOcCKD534KLOgvMb6V5ZHm1OBY3wdUuE2RJWaiQPiTjxq7jcdVG9mkWewHG8v3fqGsrRx/Qc2+qRLrBUkesZSgBnZexeSehuizMZnyrKA+QToQz2ngYayX2mu+r6zSeojtqX09TRJEbnyvodAZIlVOszrm2p8Zp27miJMtYW/2mlOQBOxTM9vxyrdV+Qo/bdhgszZR1yU+hiV1EjGbYVvpRlE6TZPpXqijY3BJLiGnBjO+cRrFb8/QtxVtgJRhnmqDnS2C/KoiZ1NFvndBa4Fr0fm+kxnEMoVZ0IKr5xeR++KnmsY2z+p63xAKEou4uPJlT6vyvPLP2NQ6bHzFFPDbtll9hka+xEtLiYVSUTqLJS23Vx5ZJhujo8VIIC/PkSorkWIPgMzRD1PddkRycefkg7h3GAXK3KWTpB4nrTNXDImhrJgwpyqGsx9pVdLxo0/DTwdls4wC7WZiGXrNoldlj9DKRerKjH10j/Q378WaS9LLg3mnxf2/LrSiqISU3N0BGSxqv787myC1Jmhse2LRg5SyJUA6fKLac0IDjZ21NIqRKEnMPcpZ0ZM7oQ=
  app: intense-hamlet-87801
  run: "./node_modules/.bin/sequelize db:migrate"
