language: node_js
node_js:
- 8.11.1
env:
- NODE_ENV=test FACEBOOK_SECRET=facebook-secret SERVER_SECRET=test-secret
services:
- postgresql
before_script:
- psql -c 'create database blog_test;' -U postgres
- "./node_modules/.bin/sequelize db:migrate"
deploy:
  provider: heroku
  api_key:
    secure: tX/8K7/zGthdI1i6PTdcORibAkGJPcAti1v/2ENTcki5p4jnFbSuu6pbSkdXGcLTnb7U7kJ11J7VqkP7fYT6RQUmxXOkDjtFk0+GhJ49I5Mytd++SADlnI3A7ZPPiuDnhdyxcJjlFQZb2It4Siy8TopXq2q98rHo6PQHRcT7VO5SIhR92ofe/c9cGaiXeuWI0LR9BY9dwel06oKNOocr3BpZkd8EZF17H560gEi2dfHMNpS9+mnWI7Rkjg6tc9BSUs9TtnhqfHXeFmXjAueu6CJFzAGOkDpbyl46GqrHK1gIiNfEF2vn2MfeeFt8hVobQWp9+ZhH+7WuCOvGMY+vRhzVzabHIc1OoT2Kt6WuzkDfEL/sRcDPo2KOmJMJR9+Lqb12c1zemYgfQD31RqYQ7VblKif/AGRfYJEQkcVMlAzKoga1t+ZdokmwrIo87zeCoJP3Aw+5ayQUbQl3A4mc9JKXXpT/MY9jit6p0L5rYrS8jb3QuE9ChkLmZtA7kpSAAP8qk2BojQPpYktl1AlzdN+iUStKsrn8V3ocGT4tBXESCR1SIcPEo7uFkK/eDgWupox9JGUlNJ5ZmtgHryYh+jyNSPY5v74WsBbYNcUyJUsAVN0h8OP2XJH42zRl3kNVmA2h0P01Vu4TE5F7oG80VRcF/SKPR/Nj5bXKzMgqzv8=
  app: intense-hamlet-87801
  run: "./node_modules/.bin/sequelize db:migrate"
